import { getStore } from '@netlify/blobs';
const json = (body,status=200)=>({status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)});
const secret=process.env.ADMIN_PASSWORD||'';
const repo=()=>({owner:process.env.GITHUB_OWNER,repo:process.env.GITHUB_REPO,branch:process.env.GITHUB_BRANCH||'main',token:process.env.GITHUB_TOKEN});
const gh=async(path,opts={})=>{const r=await fetch(`https://api.github.com${path}`,{...opts,headers:{accept:'application/vnd.github+json',authorization:`Bearer ${repo().token}`,'x-github-api-version':'2022-11-28','content-type':'application/json',...(opts.headers||{})}});const t=await r.text();let b;try{b=JSON.parse(t)}catch{b={raw:t}};if(!r.ok)throw new Error(b.message||`GitHub ${r.status}`);return b};
async function commitFile(path,content,message,encoding='utf-8'){const r=repo();if(!r.owner||!r.repo||!r.token)throw new Error('GitHub ortam değişkenleri eksik.');let sha;try{const old=await gh(`/repos/${r.owner}/${r.repo}/contents/${encodeURIComponent(path)}?ref=${encodeURIComponent(r.branch)}`);sha=old.sha}catch(e){}const body={message,content:encoding==='base64'?content:Buffer.from(content).toString('base64'),branch:r.branch};if(sha)body.sha=sha;return gh(`/repos/${r.owner}/${r.repo}/contents/${encodeURIComponent(path)}`,{method:'PUT',body:JSON.stringify(body)});}
export default async(req)=>{try{const u=new URL(req.url);if(req.method==='POST'&&u.pathname.endsWith('/login')){const b=await req.json();return b.password&&secret&&b.password===secret?json({ok:true}):json({ok:false,error:'Şifre hatalı.'},401)}
if(req.method==='GET'&&u.pathname.endsWith('/gallery')){const r=repo();if(!r.owner||!r.repo||!r.token) return json({images:[]});try{const f=await gh(`/repos/${r.owner}/${r.repo}/contents/data/gallery.json?ref=${r.branch}`);return json(JSON.parse(Buffer.from(f.content,'base64').toString('utf8')))}catch{return json({images:[]})}}
if(req.method==='POST'&&u.pathname.endsWith('/gallery')){const b=await req.json();if(!b.password||b.password!==secret)return json({error:'Yetkisiz'},401);const current=b.gallery||{images:[]};const clean={images:Array.isArray(current.images)?current.images.slice(0,100):[]};await commitFile('data/gallery.json',JSON.stringify(clean,null,2),'Update ELENİ gallery');return json({ok:true,gallery:clean})}
if(req.method==='POST'&&u.pathname.endsWith('/upload')){const b=await req.json();if(b.password!==secret)return json({error:'Yetkisiz'},401);if(!b.name||!b.data)return json({error:'Görsel eksik'},400);const safe=b.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`assets/images/gallery/${Date.now()}-${safe}`;await commitFile(path,b.data,`Add ELENİ gallery image ${safe}`,'base64');const item={src:`/${path}`,title:b.title||safe.replace(/\.[^.]+$/,'')};const r=repo();const f=await gh(`/repos/${r.owner}/${r.repo}/contents/data/gallery.json?ref=${r.branch}`);const gallery=JSON.parse(Buffer.from(f.content,'base64').toString('utf8'));gallery.images=gallery.images||[];gallery.images.push(item);await commitFile('data/gallery.json',JSON.stringify(gallery,null,2),'Update ELENİ gallery index');return json({ok:true,item,gallery})}
if(req.method==='POST'&&u.pathname.endsWith('/delete')){const b=await req.json();if(b.password!==secret)return json({error:'Yetkisiz'},401);const r=repo();const f=await gh(`/repos/${r.owner}/${r.repo}/contents/data/gallery.json?ref=${r.branch}`);const gallery=JSON.parse(Buffer.from(f.content,'base64').toString('utf8'));gallery.images=(gallery.images||[]).filter(x=>x.src!==b.src);await commitFile('data/gallery.json',JSON.stringify(gallery,null,2),'Remove ELENİ gallery image');if(b.src&&b.src.startsWith('/')){try{const p=b.src.slice(1);const old=await gh(`/repos/${r.owner}/${r.repo}/contents/${encodeURIComponent(p)}?ref=${r.branch}`);await gh(`/repos/${r.owner}/${r.repo}/contents/${encodeURIComponent(p)}`,{method:'DELETE',body:JSON.stringify({message:'Remove ELENİ gallery image file',sha:old.sha,branch:r.branch})})}catch{}}return json({ok:true,gallery})}
return json({error:'Bulunamadı'},404)}catch(e){return json({error:e.message},500)}};
